todo/urls.py
from django.conf.urls import url
from todo import views

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.signin, name='login'),
    url(r'^$', views.main, name='main'),
    url(r'^list/$', views.todo_list, name='todo_list'),
    url(r'^create/$', views.todo_create, name='todo_create'),
    url(r'^edit/(?P<pk>\d+)/$', views.todo_edit, name='todo_edit'),
    url(r'^view/(?P<pk>\d+)/$', views.todo_view, name='todo_view'),
    url(r'^delete/(?P<pk>\d+)/$', views.todo_delete, name='todo_delete'),
    url(r'^complete/(?P<pk>\d+)/$', views.todo_complete, name='todo_complete'),
    url(r'^undo/complete/(?P<pk>\d+)/$', views.undo_complete, name='undo_complete'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls import url

urlpatterns = [
    #url(r'^accounts/login/', auth_views.login, name='login', kwargs={'template_name': 'login.html'}),
    url(r'^logout/', auth_views.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
]

todo/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator

class List(models.Model):
    PRIORITY_CHOICES = ((1, '낮음'), (2,'보통'), (3,'높음'))
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    context = models.TextField()
    priority = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(3)], choices=PRIORITY_CHOICES)
    created_date = models.DateField(default=timezone.now)
    completed_date = models.DateField(blank=True, null=True)
    deadline = models.DateField(blank=True, null=True)

    def complete(self):
        self.completed_date = timezone.now()
        self.save()

    def undo_complete(self):
        self.completed_date = None
        self.save()

    def __str__(self):
        return self.title

todo/forms.py
from django import forms
from django.contrib.auth.models import User
from todo.models import List

class SignupForm(forms.ModelForm):
    password = forms.CharField(
        label='비밀번호',
        strip=False,
        widget=forms.PasswordInput()
    )

    class Meta:
        model = User
        fields = ('username', 'password', 'email')
        labels = {
            'username': '아이디',
            'password': '비밀번호',
            'email': '이메일'
        }

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['username'].help_text = '문자, 숫자 및 @/./+/-/_ 문자만 포함될 수 있습니다.'
        self.fields['username'].error_messages['invalid'] = '올바른 아이디를 입력하십시오. 문자, 숫자 및 @/./+/-/_ 문자만 포함될 수 있습니다.'
        self.fields['username'].error_messages['unique'] = '이미 존재하는 아이디입니다.'
        self.fields['email'].error_messages['invalid'] = '올바른 이메일주소를 입력해주세요.'


class LoginForm(forms.ModelForm):
    password = forms.CharField(
        label = '비밀번호',
        strip=False,
        widget=forms.PasswordInput()
    )

    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control mb-2'
        self.fields['username'].widget.attrs['placeholder'] = 'ID'
        self.fields['password'].widget.attrs['class'] = 'form-control mb-2'
        self.fields['password'].widget.attrs['placeholder'] = 'PASSWORD'


class TodoForm(forms.ModelForm):
    class Meta:
        model = List
        fields = ('title', 'context', 'priority', 'deadline')
        labels = {
            'title': '제목',
            'context': '내용',
            'priority': '우선순위',
            'deadline': '마감기한'
        }

    def __init__(self, *args, **kwargs):
        super(TodoForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['context'].widget.attrs['class'] = 'form-control'
        self.fields['priority'].widget.attrs['class'] = 'form-control'
        self.fields['deadline'].widget.attrs['class'] = 'form-control'
        self.fields['priority'].initial = 2
        self.fields['title'].widget.attrs['autocomplete'] = 'off'
        self.fields['deadline'].widget.attrs['autocomplete'] = 'off'
        self.fields['deadline'].error_messages['invalid'] = '올바른 날짜를 입력해주세요.'

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.utils import timezone

from django.contrib.auth.models import User
from todo.models import List
from todo.forms import SignupForm, LoginForm, TodoForm

def main(request):
    if not request.user.is_authenticated:
        return redirect('login')
    else:
        return redirect('todo_list')

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(**form.cleaned_data)
            login(request, new_user)
            return redirect('main')
    else:
        form = SignupForm()
    return render(request, 'registration/signup.html', {'form': form})

def signin(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username, password = password)
        if user is not None:
            login(request, user)
            return redirect('main')
        else:
            return HttpResponse("<script>alert('로그인 실패. 다시 시도해주세요.');history.back();</script>")
    else:
        form = LoginForm()
        return render(request, 'registration/login.html', {'form': form})


@login_required(login_url='/')
def todo_list(request):
    if request.method == "POST":
        filter1 = request.POST.get('filter1')
        filter2 = request.POST.get('filter2')
        column = request.POST.get('column')
        sort = request.POST.get('sort')
        mode = request.POST.get('mode')
        checkOne = request.POST.getlist('checkOne')

        check_lists = List.objects.filter(user=request.user, pk__in=checkOne)
        if mode == "complete":
            for check_list in check_lists:
                check_list.complete()
        elif mode == "delete":
            for check_list in check_lists:
                check_list.delete()

        response = redirect('todo_list')
        response['Location'] += '?filter1='+filter1+'&filter2='+filter2+'&column='+column+'&sort='+sort
        return response
    else:
        column = request.GET.get('column', 'pk')  #번호(등록순서),우선순위,마감기한
        sort = request.GET.get('sort', '')  #asc,desc
        today = timezone.now()
        filter1 = request.GET.get('filter1', 'all')
        filter2 = request.GET.get('filter2', 'all')
        
        lists = List.objects.filter(user=request.user)

        if filter1 == 'completed':
            lists = lists.filter(completed_date__isnull=False)
        elif filter1 == 'incompleted':
            lists = lists.filter(completed_date__isnull=True)

        if filter2 == 'none':
            lists = lists.filter(deadline__isnull=True)
        elif filter2 == 'before':
            lists = lists.filter(deadline__gte=today)
        elif filter2 == 'after':
            lists = lists.filter(deadline__lt=today)

        lists = lists.order_by(sort+column)

        incompleted_in_deadline_count = List.objects.filter(user=request.user, deadline__lt=today,
                                        completed_date__isnull=True).count()

        return render(request, 'todo/list.html', {
            'menu': 'list', 'lists': lists, 'incompleted_count': incompleted_in_deadline_count,
            'filter1': filter1, 'filter2': filter2,
            'column': column, 'sort': sort
        })

@login_required(login_url='/')
def todo_create(request):
    if request.method == "POST":
        form = TodoForm(request.POST)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.user = request.user
            todo.save()
            return redirect('todo_view', todo.pk)
    else:
        form = TodoForm()
    return render(request, 'todo/edit.html', {'menu': 'list', 'form': form})

@login_required(login_url='/')
def todo_edit(request, pk):
    todo = List.objects.get(user=request.user, pk=pk)
    if request.method == "POST":
        form = TodoForm(request.POST, instance=todo)
        if form.is_valid():
            form.save()
            return redirect('todo_view', todo.pk)
    else:
        form = TodoForm(instance=todo)
    return render(request, 'todo/edit.html', {'menu': 'list', 'form': form, 'pk': pk})

@login_required(login_url='/')
def todo_view(request, pk):
    todo = get_object_or_404(List, user=request.user, pk=pk)
    return render(request, 'todo/view.html', {'menu': 'list', 'todo': todo, 'pk': pk})

@login_required(login_url='/')
def todo_delete(request, pk):
    todo = List.objects.get(user=request.user, pk=pk)
    todo.delete()
    return redirect('todo_list')

@login_required(login_url='/')
def todo_complete(request, pk):
    todo = List.objects.get(user=request.user, pk=pk)
    todo.complete()
    return redirect('todo_view', todo.pk)

@login_required(login_url='/')
def undo_complete(request, pk):
    todo = List.objects.get(user=request.user, pk=pk)
    todo.undo_complete()
    return redirect('todo_view', todo.pk)

todo/templates/todo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
	<head>
		<meta charset="utf-8">
		<title>Todo</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
		<link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/flatly/bootstrap.min.css" rel="stylesheet" integrity="sha384-T5jhQKMh96HMkXwqVMSjF3CmLcL1nT9//tCqu9By5XSdj7CwR0r+F3LTzUdfkkQf" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static 'css/todo.css' %}">
		<script src="{% static 'js/todo.js' %}"></script>
		<!-- datepicker -->
		<link rel="stylesheet" type="text/css" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css"/>
		<script type="text/javascript" src="//code.jquery.com/jquery-1.12.4.js"></script>
		<script type="text/javascript" src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
		<!-- end datepicker -->
	</head>
	<body>
		{% include 'todo/menu.html' %}

		<div class="container-fluid">
		{% block content %}
		{% endblock %}
		</div>
	</body>
</html>

todo/templates/todo/edit.html
{% extends 'todo/base.html' %}

{% block content %}
<div class="wrapper shadow">
	<h2 class="mb-3">TODO {% if not pk %}등록{% else %}수정{% endif %}</h2>
	<form method="POST">
		{% csrf_token %}
		<div class="table-responsive">
			<table class="table table-bordered text-center text-nowrap">
				<colgroup>
					<col width="10%"/>
					<col width="90%"/>
				</colgroup>
				{% for field in form %}
				<tr>
					<td>{{ field.label }}{% if field.field.required %}<span class="text-danger">*</span>{% endif %}</td>
					<td>{{ field }}</td>
				</tr>
				{% if field.errors %}
				<tr><td colspan="2"><strong class="text-danger">{{ field.errors|striptags }}</strong></td><tr>
				{% endif %}
				{% endfor %}
			</table>
		</div>
		<div class="text-center">
			<input type="submit" class="btn btn-primary" style="width:49%" value="{% if not pk %}등록{% else %}수정{% endif %}"/>
			<input type="button" class="btn btn-primary" style="width:49%" onclick="return cancelCheck();" value="취소"/>
		<div>
	</form>
</div>
<script type="text/javascript">
$('#id_deadline').datepicker({
	dateFormat: 'yy-mm-dd' //Input Display Format 변경
	,showOtherMonths: true //빈 공간에 현재월의 앞뒤월의 날짜를 표시
	,showMonthAfterYear:true //년도 먼저 나오고, 뒤에 월 표시
	,changeYear: true //콤보박스에서 년 선택 가능
	,changeMonth: true //콤보박스에서 월 선택 가능                
	,yearSuffix: "년" //달력의 년도 부분 뒤에 붙는 텍스트
	,monthNamesShort: ['1','2','3','4','5','6','7','8','9','10','11','12'] //달력의 월 부분 텍스트
	,monthNames: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'] //달력의 월 부분 Tooltip 텍스트
	,dayNamesMin: ['일','월','화','수','목','금','토'] //달력의 요일 부분 텍스트
	,dayNames: ['일요일','월요일','화요일','수요일','목요일','금요일','토요일'] //달력의 요일 부분 Tooltip 텍스트
	,minDate: "today" //최소 선택일자(-1D:하루전, -1M:한달전, -1Y:일년전)
});
</script>
{% endblock %}

todo/templates/todo/list.html
{% extends 'todo/base.html' %}

{% block content %}
{% if incompleted_count and filter1 != 'incompleted' %}
<div class="alert-wrapper alert alert-light alert-dismissible">
	<button type="button" class="close" data-dismiss="alert" aria-label="close">&times;</button>
	<a href="?filter1=incompleted&filter2=after&column={{column}}&sort={{sort}}" class="alert-link">마감기한 내에 완료하지 못한 TODO({{ incompleted_count }})</strong></a>가 있습니다.
</div>
{% endif %}

<div class="wrapper shadow">
	<a class="btn btn-primary mb-2" href="{% url 'todo_create' %}">TODO 추가</a>
	<div class="card">
		<div class="card-body py-2">
			<a class="card-link {% if filter1 == 'all' %}active{% endif %}" href="?filter1=all&filter2=all&column={{column}}&sort={{sort}}">전체</a>
			<a class="card-link {% if filter1 == 'completed' %}active{% endif %}" href="?filter1=completed&filter2=all&column={{column}}&sort={{sort}}">완료</a>
			<a class="card-link {% if filter1 == 'incompleted' %}active{% endif %}" href="?filter1=incompleted&filter2=all&column={{column}}&sort={{sort}}">미완료</a>
		</div>
	</div>
	<ul class="nav nav-tabs mt-2">
		<li class="nav-item">
			<a class="nav-link px-3 py-1 {% if filter2 == 'all' %}active{% endif %}" href="?filter1={{filter1}}&filter2=all&column={{column}}&sort={{sort}}">전체</a>
		</li>
		<li class="nav-item">
			<a class="nav-link px-3 py-1 {% if filter2 == 'none' %}active{% endif %}" href="?filter1={{filter1}}&filter2=none&column={{column}}&sort={{sort}}">마감없음</a>
		</li>
		<li class="nav-item">
			<a class="nav-link px-3 py-1 {% if filter2 == 'before' %}active{% endif %}" href="?filter1={{filter1}}&filter2=before&column={{column}}&sort={{sort}}">마감전</a>
		</li>
		<li class="nav-item">
			<a class="nav-link px-3 py-1 {% if filter2 == 'after' %}active{% endif %}" href="?filter1={{filter1}}&filter2=after&column={{column}}&sort={{sort}}">마감지남</a>
		</li>
	</ul>
	<form id="listForm" method="POST" action="">
		<input type="hidden" name="filter1" value="{{ filter1 }}"/>
		<input type="hidden" name="filter2" value="{{ filter2 }}"/>
		<input type="hidden" name="column" value="{{ column }}"/>
		<input type="hidden" name="sort" value="{{ sort }}"/>
		<input type="hidden" name="mode" value=""/>
		{% csrf_token %}
		<div class="table-responsive">
			<table class="table text-center text-nowrap">
				<colgroup>
					<col width="5%"/>
					<col width="10%"/>
					<col width="10%"/>
					<col />
					<col width="20%"/>
					<col width="10%"/>
				</colgroup>
				<thead>
					<tr>
						<th><input type="checkbox" name="checkAll"/></th>
						<th>등록일자
							<a href="?filter1={{filter1}}&filter2={{filter2}}&column=pk&sort=">▲</a><a href="?filter1={{filter1}}&filter2={{filter2}}&column=pk&sort=-">▼</a>
						</th>
						<th>우선순위
							<a href="?filter1={{filter1}}&filter2={{filter2}}&column=priority&sort=">▲</a><a href="?filter1={{filter1}}&filter2={{filter2}}&column=priority&sort=-">▼</a>
						</th>
						<th>제목</th>
						<th>마감기한
							<a href="?filter1={{filter1}}&filter2={{filter2}}&column=deadline&sort=">▲</a><a href="?filter1={{filter1}}&filter2={{filter2}}&column=deadline&sort=-">▼</a>
						</th>
						<th>상태</th>
					</tr>
				</thead>
				<tbody>
					{% if not lists %}
					<tr>
						<td colspan="6">등록된 TODO가 없습니다.</td>
					</tr>
					{% else %}
					{% for list in lists %}
					<tr>
						<td><input type="checkbox" name="checkOne" value="{{ list.pk }}"/></td>
						<td>{{ list.created_date|date:"Y-m-d" }}</td>
						<!--<td>{% if column == 'pk' and sort == '-' %}{{ forloop.revcounter }}{% else %}{{ forloop.counter }}{% endif %}</td>-->
						<td>{{ list.get_priority_display }}</td>
						<td class="text-left" style="text-overflow:ellipsis;overflow:hidden;" title="{{ list }}"><a href="{% url 'todo_view' pk=list.pk %}">{{ list }}</a></td>
						<td>{{ list.deadline|date:"Y-m-d" }}</td>
						{% if list.completed_date %}
						<td>
							<strong class="text-success">완료</strong>
						</td>
						{% else %}
						<td>
							<strong class="text-danger">미완료</strong>
						</td>
						{% endif %}
					</tr>
					{% endfor %}
					{% endif %}
				</tbody>
			</table>
		</div>
		<div class="clearfix">
			<input type="button" class="btn btn-primary px-5" onClick="setMode('complete');" value="완료"/>
			<input type="button" class="btn btn-primary px-5" onClick="setMode('delete');" value="삭제"/>
		</div>
	</form>
</div>
<script type="text/javascript">
function allCheckFunc( obj ) {
	$("[name=checkOne]").prop("checked", $(obj).prop("checked") );
}

function oneCheckFunc( obj )
{
	var allObj = $("[name=checkAll]");
	var objName = $(obj).attr("name");
	
	if( $(obj).prop("checked") )
	{
		checkBoxLength = $("[name="+ objName +"]").length;
		checkedLength = $("[name="+ objName +"]:checked").length;
		
		if( checkBoxLength == checkedLength ) {
			allObj.prop("checked", true);
		} else {
			allObj.prop("checked", false);
		}
	}
	else
	{
		allObj.prop("checked", false);
	}
}

$(function(){
	$("[name=checkAll]").click(function(){
		allCheckFunc( this );
	});
	$("[name=checkOne]").each(function(){
		$(this).click(function(){
			oneCheckFunc( $(this) );
		});
	});
});

function setMode(mode) {
	if(!$("input:checkbox[name='checkOne']").is(":checked")){
		alert("선택된 TODO가 없습니다.");
		return 0;
	}
	var frm = document.getElementById("listForm");
	frm.mode.value = mode;
	frm.submit();
}
</script>
{% endblock %}

todo/templates/todo/menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
	<a class="navbar-brand mb-0 h1" href="{% url 'main' %}">TODO</a>
	<ul class="navbar-nav ml-auto">
		{% if not request.user.is_authenticated %}
		<li class="nav-item">
			<a class="nav-link" href="{% url 'login' %}"><strong>로그인</strong></a>
		</li>
		{% else %}
		<li class="nav-item">
			<a class="nav-link" href="{% url 'logout' %}"><strong>{{ request.user }}님 로그아웃</strong></a>
		</li>
		{% endif %}
	</ul>
</nav>

todo/templates/todo/view.html
{% extends 'todo/base.html' %}

{% block content %}
<div class="wrapper shadow">
	<h2 class="mb-3">TODO 조회</h2>
		<div class="table-responsive">
			<table class="table table-bordered text-nowrap">
				<colgroup>
					<col width="10%"/>
					<col width="90%"/>
				</colgroup>
				<tr>
					<td class="text-center">제목</td>
					<td>{{ todo.title }}</td>
				</tr>
				<tr height="200px">
					<td class="text-center">내용</td>
					<td><pre style="white-space: pre-wrap;">{{ todo.context }}</pre></td>
				</tr>
				<tr>
					<td class="text-center">우선순위</td>
					<td>{{ todo.get_priority_display }}</td>
				</tr>
				<tr>
					<td class="text-center">마감기한</td>
					<td>{{ todo.deadline|date:"Y-m-d" }}</td>
				</tr>
			</table>
		</div>
		<div class="clearfix">
			<div class="float-left">
			<a class="btn btn-primary px-4" href="{% url 'todo_list' %}">목록</a>
			</div>
			<div class="float-right">
			{% if not todo.completed_date %}
			<a class="btn btn-primary px-4" href="{% url 'todo_edit' pk=pk %}">수정</a>
			<a class="btn btn-primary px-4" href="{% url 'todo_complete' pk=pk %}">완료</a>
			{% else %}
			<a class="btn btn-primary px-4" href="{% url 'undo_complete' pk=pk %}">완료취소</a>
			{% endif %}
			<a class="btn btn-primary px-4" href="{% url 'todo_delete' pk=pk %}" onclick="return deleteCheck();">삭제</a>
			</div>
		</div>
</div>
{% endblock %}